spring:
  datasource:
    url: ${jushu.datasource.dev.url}
    username: ${jushu.datasource.dev.username}
    password: ${jushu.datasource.dev.password}

mybatis:
  type-aliases-package: com.chen.mapper